name = "aiswelcome"
main = "apps/worker/src/index.ts"
compatibility_date = "2025-07-26"
compatibility_flags = ["nodejs_compat"]

# Routes
[[routes]]
pattern = "aiswelcome.franzai.com/*"
zone_name = "franzai.com"

# D1 Database
[[d1_databases]]
binding = "DB"
database_name = "aiswelcome-db"
database_id = "0882f8d9-0c8b-45bd-8640-1ced3a6e7d2d"

# KV Namespaces
[[kv_namespaces]]
binding = "SESSIONS"
id = "b56e1bb7a5c747e5925d3ae8f18511f3"

# R2 Buckets
[[r2_buckets]]
binding = "UPLOADS"
bucket_name = "aiswelcome-uploads"

[[r2_buckets]]
binding = "AVATARS"
bucket_name = "aiswelcome-avatars"

# Durable Objects
[[durable_objects.bindings]]
name = "RATE_LIMITER"
class_name = "RateLimiter"

[[migrations]]
tag = "v1"
new_classes = ["RateLimiter"]

# Environment Variables
[vars]
ENVIRONMENT = "production"