name = "aiswelcome"
main = "apps/worker/src/index-minimal.ts"
compatibility_date = "2025-07-26"

# Routes
[[routes]]
pattern = "aiswelcome.franzai.com/*"
zone_name = "franzai.com"

# Environment Variables
[vars]
ENVIRONMENT = "production"