name = "aiswelcome"
main = "apps/worker/src/index.ts"
compatibility_date = "2025-07-26"
compatibility_flags = ["nodejs_compat"]

# Routes
[[routes]]
pattern = "aiswelcome.franzai.com/*"
zone_name = "franzai.com"

# Environment Variables
[vars]
ENVIRONMENT = "production"